org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
minecraft_version=26.1.1
neo_version=26.1.1.0-beta
mod_id=grid_recipe_filter
mod_name=Grid Recipe Filter
mod_version=0.3.0
mod_group_id=io.github.gridrecipefilter
